<a href="https://colab.research.google.com/github/DV-11/SpanishVarietyDiscrimination/blob/main/Spanish_Sentence_Dataset_Info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import collections

In [2]:
!git clone https://github.com/DV-11/SpanishDialectDiscrimination.git

Cloning into 'SpanishDialectDiscrimination'...
remote: Enumerating objects: 1047, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 1047 (delta 95), reused 66 (delta 20), pack-reused 820 (from 1)
Receiving objects: 100% (1047/1047), 26.43 MiB | 5.87 MiB/s, done.
Resolving deltas: 100% (472/472), done.

In [3]:
di = pd.read_csv('/content/SpanishDialectDiscrimination/Data/Dialogue_Info.csv')
di.head()

,Text_ID,Country,Recording_Date,Transcription_Date,E_sex,E_age_group,E_age,E_education,E_occupation,E_origin_city,E_origin_state,E_origin_country,I_sex,I_age_group,I_age,I_education,I_occupation,I_origin_city,I_origin_state,I_origin_country
0,ALCA_H11_037,Spain,1998-06-25,2011-03-23,M,3,NaN,High,Professor,NaN,NaN,Spain,M,2,33,Low,Retail,Guadalajara,Castilla-La Mancha,Spain
1,GUAD_H11_086,Mexico,2017-10-02,2017-11-08,F,1,21.0,High,Student,Tlaquepaque,Jalisco,Mexico,M,1,23,Low,Car cleaner,Guadalajara,Jalisco,Mexico
2,ALCA_H12_019,Spain,1991-04-10,2011-04-13,M,2,NaN,Low,Mechanic,NaN,NaN,Spain,M,1,25,Medium,Student,Madrid,Madrid,Spain
3,GUAD_H12_098,Mexico,2019-10-20,2020-02-28,F,1,20.0,Medium,Retail,Guadalajara,Jalisco,Mexico,M,1,21,High,Student,Autlán de Navarro,Jalisco,Mexico
4,ALCA_H13_001,Spain,1991-03-15,2011-03-15,N,2,42.0,Low,Mechanic,NaN,NaN,Spain,M,1,32,High,Legal Advisor,Alcalá de Henares,Madrid,Spain

In [ ]:
ss = pd.read_csv('/content/SpanishDialectDiscrimination/Data/Spanish_Sentence_Dataset.csv')
ss.head()

,Text ID,Line,Speaker,Raw,PS,MS,English,Type,Notes,Unnamed: 9
0,ALCA_H11_037,10,B,¿qué has hecho hoy? / cuéntame <silencio/> cur...,¿Qué has hecho hoy? Cuéntame - Currar y pasar ...,¿Qué hiciste hoy? Cuéntame - Chambear y pasar ...,What did you do today? Tell me - I worked and ...,Both,NaN,NaN
1,ALCA_H11_037,11,I,he cambiado / porque la otra vez / la niña est...,"He cambiado, porque la niña estaba en el coleg...","Cambié, porque la niña estaba en la escuela, p...","I changed, because the girl was in school, but...",Both,NaN,NaN
2,ALCA_H11_037,12,I,hoy me ha tocado / irme con el coche a un pueb...,Hoy me ha tocado irme con el coche a un pueblo...,Hoy me tocó irme con el carro a un pueblo a re...,Today I had to go to a town by car to deliver ...,Both,NaN,NaN
3,ALCA_H11_037,14,I,normalmente si estoy solo si tengo jaleo pues ...,"Normalmente, si estoy solo o si tengo jaleo, p...","Normalmente, si estoy solo o si hay alboroto, ...","Usually, if I'm alone or if there's chaos, I d...",Lexical,https://www.jergasdehablahispana.org/index.php...,NaN
4,ALCA_H11_037,16,I,le vamos a coger el gustillo,Le vamos a coger el gustillo,Le vamos a agarrar el gustito,We're going to take a liking to it,Lexical,NaN,NaN

In [ ]:
id_count = ss['Text ID'].value_counts().to_dict()

mx_ids = set(di[di['Country']=='Mexico']['Text_ID'])

es_ids = mex_ids = set(di[di['Country']=='Spain']['Text_ID'])

In [ ]:
mx_id_counts = {k: id_count[k] for k in mx_ids}
es_id_counts = {k: id_count[k] for k in es_ids}

In [ ]:
print("Number of sentences originally from Peninsular Spanish texts:", sum(es_id_counts.values()))
print("Number of sentences originally from Mexican Spanish texts:", sum(mx_id_counts.values()))

Number of sentences originally from Peninsular Spanish texts: 114
Number of sentences originally from Mexican Spanish texts: 94

# Characteristic Words

In [ ]:
so = pd.read_csv('/content/SpanishDialectDiscrimination/Data/Sentences_Only.csv')
so.head()

,PS,MS,English
0,¿Qué has hecho hoy? Cuéntame - Currar y pasar ...,¿Qué hiciste hoy? Cuéntame - Chambear y pasar ...,What did you do today? Tell me - I worked and ...
1,"He cambiado, porque la niña estaba en el coleg...","Cambié, porque la niña estaba en la escuela, p...","I changed, because the girl was in school, but..."
2,Hoy me ha tocado irme con el coche a un pueblo...,Hoy me tocó irme con el carro a un pueblo a re...,Today I had to go to a town by car to deliver ...
3,"Normalmente, si estoy solo o si tengo jaleo, p...","Normalmente, si estoy solo o si hay alboroto, ...","Usually, if I'm alone or if there's a commotio..."
4,Le vamos a coger el gustillo,Le vamos a agarrar el gustito,We're going to take a liking to it

In [ ]:
ps_df = so['PS'].copy()
ps_df = ps_df.dropna()

ms_df = so['MS'].copy()
ms_df = ms_df.dropna()

In [ ]:
ps_count = collections.Counter([y for x in ps_df.values.flatten() for y in x.split()])
ms_count = collections.Counter([y for x in ms_df.values.flatten() for y in x.split()])

ps_count.most_common(60)

[('que', 47),
 ('de', 46),
 ('el', 42),
 ('a', 42),
 ('y', 41),
 ('la', 32),
 ('en', 32),
 ('no', 29),
 ('ha', 29),
 ('me', 26),
 ('un', 24),
 ('-', 23),
 ('con', 23),
 ('muy', 20),
 ('lo', 19),
 ('¿Y', 18),
 ('las', 17),
 ('he', 16),
 ('¿Qué', 15),
 ('los', 15),
 ('han', 15),
 ('te', 15),
 ('o', 14),
 ('qué', 14),
 ('vosotros', 14),
 ('se', 14),
 ('mi', 14),
 ('coche', 13),
 ('para', 13),
 ('pero', 12),
 ('Yo', 12),
 ('más', 11),
 ('es', 11),
 ('una', 11),
 ('A', 11),
 ('hecho', 10),
 ('porque', 10),
 ('por', 10),
 ('ya', 9),
 ('todo', 9),
 ('era', 9),
 ('has', 7),
 ('mucho', 7),
 ('pues', 7),
 ('le', 7),
 ('eso', 7),
 ('yo', 7),
 ('del', 6),
 ('tú', 6),
 ('gente', 6),
 ('os', 6),
 ('al', 6),
 ('veces', 6),
 ('bien', 6),
 ('coger', 5),
 ('desde', 5),
 ('En', 5),
 ('Cuando', 5),
 ('colegio', 5),
 ('cuando', 5)]

In [ ]:
ms_count.most_common(50)

[('que', 50),
 ('la', 49),
 ('de', 47),
 ('a', 42),
 ('y', 40),
 ('en', 33),
 ('no', 30),
 ('el', 26),
 ('me', 25),
 ('-', 23),
 ('con', 23),
 ('un', 22),
 ('¿Y', 18),
 ('lo', 18),
 ('se', 18),
 ('muy', 17),
 ('las', 16),
 ('te', 16),
 ('¿Qué', 15),
 ('o', 14),
 ('ustedes', 14),
 ('los', 14),
 ('carro', 13),
 ('qué', 13),
 ('para', 13),
 ('mi', 13),
 ('pero', 12),
 ('más', 11),
 ('es', 11),
 ('una', 11),
 ('por', 11),
 ('Yo', 11),
 ('porque', 10),
 ('A', 10),
 ('todo', 9),
 ('ya', 8),
 ('bien', 8),
 ('mucho', 7),
 ('le', 7),
 ('eso', 7),
 ('yo', 7),
 ('era', 7),
 ('estaba', 6),
 ('pues', 6),
 ('tú', 6),
 ('gente', 6),
 ('escuela', 6),
 ('al', 6),
 ('veces', 6),
 ('Me', 6)]

In [ ]:
ps_words = set(ps_count.keys()) - set(ms_count.keys())
ms_words = set(ms_count.keys()) - set(ps_count.keys())

{'"ganamos".',
 '"gané",',
 'Agarraba',
 'Agarraran',
 'Agarras',
 'Aggaré',
 'Ahorita',
 'Cambié,',
 'Causó',
 'Chambear',
 'Chín,',
 'Cocheras',
 'Dejé',
 'Dió',
 'Mejoró',
 'Nomás',
 'Okay,',
 'Tardé',
 'Tomar',
 'Ustedes',
 'Vente',
 'Vénganse',
 'acabó',
 'acuerdo',
 'agarrar',
 'agarrarle',
 'agarras',
 'agüitaba',
 'ahorita',
 'ahorita?',
 'alboroto,',
 'aluminio',
 'ampliaron',
 'anda',
 'andar',
 'antros',
 'apartamento',
 'apartamento,',
 'apartamento.',
 'aqui',
 'arreglaron',
 'así,',
 'bajaron?',
 'baldío',
 'banqueta',
 'banquetas',
 'boleto',
 'bronca',
 'buena',
 'cacho',
 'calificaciones',
 'calificaciones?',
 'cambiaron,',
 'cambiaron?',
 'caminando',
 'camiones',
 'camión',
 'canchas',
 'carnal',
 'carrilla',
 'carrito',
 'carro',
 'carro,',
 'carro.',
 'carros',
 'cañona',
 'celebran',
 'celular?',
 'chamacos',
 'chamarra',
 'chance',
 'chava',
 'chava?',
 'chavo',
 'chavos',
 'checar',
 'cheve',
 'chico,',
 'chico?',
 'chicos?',
 'chida',
 'chido.',
 'chiquito,',
 'codita',
 'comido',
 'compas',
 'comprarse',
 'compró',
 'computadora',
 'computadora?-',
 'computadoras',
 'confió',
 'conocen?',
 'construyeron',
 'corrí',
 'cositas',
 'cotorreando',
 'crecieron',
 'cuadras',
 'cuates?',
 'culparon',
 'curitas.',
 'decidí',
 'dejarles',
 'dejé',
 'dejó',
 'departamento,',
 'desmadre',
 'dijeron',
 'dijiste',
 'empezaron',
 'enoja',
 'enojaba',
 'enojas',
 'enojes',
 'enojó?',
 'enojón,',
 'entendí',
 'escuela',
 'escuela,',
 'escuela.',
 'escuela?',
 'espacios',
 'estacionado,',
 'estacionamiento',
 'estacionamientos',
 'estan',
 'estudié',
 'estuvieron',
 'estuvo',
 'extraño',
 'flojeando',
 'flojera',
 'flojera.',
 'flojo',
 'focos',
 'fresa',
 'frijoles',
 'fueron',
 'fuí',
 'gachas',
 'gacho',
 'ganó',
 'girasol',
 'gustito',
 'gustó',
 'gustó!',
 'gustó.',
 'güera,',
 'hablar.',
 'hacian',
 'hice',
 'hiciera?',
 'hicieron',
 'hicieron?',
 'hiciste',
 'hiciste?',
 'hizo',
 'ibamos',
 'iban',
 'invitan?',
 'jalada,',
 'jugé',
 'lana',
 'lastimé',
 'licencia',
 'linda',
 'lindas',
 'llevaban',
 'lote',
 'maestro',
 'malas',
 'manejaba',
 'manejar',
 'manejar,',
 'manejo',
 'marcaste?',
 'menso!',
 'mesero',
 'metiche',
 'modo',
 'molida',
 'montón',
 'moronga',
 'morros',
 'nana',
 'neta',
 'nomás',
 'notó',
 'ocupa',
 'ofendiste',
 'onda',
 'organizan',
 'organizan?',
 'padre!',
 'padrísimo.',
 'pagarles',
 'panteón',
 'pasaba',
 'pasaban?',
 'pasada',
 'pastel',
 'pasó',
 'pasó?',
 'penal?',
 'pingos',
 'planearon',
 'platicabamos',
 'platican',
 'platicar',
 'platicas',
 'pluma,',
 'poquito',
 'poquito.',
 'portó',
 'pueden',
 'puesto',
 'páprika,',
 'quitaron',
 'recogiamos',
 'refrigerador',
 'reprobar.',
 'salió',
 'semillitas',
 'semillitas,',
 'son',
 'son?',
 'subteráneas',
 'suelen',
 'tarea',
 'tienen',
 'tocó',
 'tomamos',
 'tomo',
 'torta',
 'torta,',
 'tuvo',
 'ustedes',
 'ustedes?',
 'vale',
 'valió',
 'vendí',
 'verian',
 'vi,',
 'vino',
 'ví',
 '¡Híjole!',
 '¡Orale!',
 '¡Órale!',
 '¿Buscaron',
 '¿Hacen',
 '¿Han',
 '¿Salen',
 '¿Tienen',
 '¿Ustedes'}

In [ ]:
# Source - https://stackoverflow.com/a
# Posted by Bhargav Rao, modified by community. See post 'Timeline' for change history
# Retrieved 2025-12-16, License - CC BY-SA 3.0

list(filter(lambda d: d['type'] in keyValList, exampleSet))
[{'type': 'type2'}, {'type': 'type2'}, {'type': 'type3'}]

In [ ]:

collections.OrderedDict({k:v for k,v in ps_count.items() if k not in ps_words})

OrderedDict([('¿Qué', 15),
             ('has', 7),
             ('hecho', 10),
             ('hoy?', 1),
             ('Cuéntame', 1),
             ('-', 23),
             ('y', 41),
             ('pasar', 2),
             ('mucho', 7),
             ('calor', 3),
             ('porque', 10),
             ('la', 32),
             ('niña', 1),
             ('estaba', 3),
             ('en', 32),
             ('el', 42),
             ('pero', 12),
             ('ya', 9),
             ('no', 29),
             ('Hoy', 2),
             ('me', 26),
             ('irme', 1),
             ('con', 23),
             ('coche', 13),
             ('a', 42),
             ('un', 24),
             ('pueblo', 2),
             ('repartir', 1),
             ('algunas', 1),
             ('tal', 4),
             ('Normalmente,', 1),
             ('si', 4),
             ('estoy', 2),
             ('solo', 4),
             ('o', 14),
             ('tengo', 3),
             ('pues', 7),
             ('salgo', 1),
             ('del', 6),
             ('trabajo', 2),
             ('Le', 1),
             ('vamos', 2),
             ('¿Y', 18),
             ('qué', 14),
             ('para', 13),
             ('combatir', 1),
             ('calor?', 1),
             ('cambios', 2),
             ('más', 11),
             ('importantes', 1),
             ('recuerdas', 3),
             ('tú', 6),
             ('ciudad,', 1),
             ('desde', 5),
             ('que', 47),
             ('eras', 3),
             ('ahora?', 2),
             ('Pues', 4),
             ('de', 46),
             ('gente', 6),
             ('En', 5),
             ('descanso,', 1),
             ('ibas', 1),
             ('comer', 2),
             ('lo', 19),
             ('fuera', 2),
             ('Eso', 2),
             ('es', 11),
             ('hacen', 1),
             ('los', 15),
             ('niños.', 1),
             ('Hacer', 1),
             ('tus', 3),
             ('No', 2),
             ('hemos', 1),
             ('tenido', 4),
             ('cómo', 3),
             ('Cuando', 5),
             ('terminaba', 1),
             ('las', 17),
             ('seis,', 1),
             ('estabas', 2),
             ('calle,', 2),
             ('habías', 2),
             ('sería', 1),
             ('bueno', 1),
             ('se', 14),
             ('casi', 3),
             ('siempre', 3),
             ('mismos', 1),
             ('amigos?', 1),
             ('Normalmente', 1),
             ('mejor', 3),
             ('llevo', 2),
             ('gusta', 4),
             ('hacer', 4),
             ('cuando', 5),
             ('familia?', 2),
             ('no?', 3),
             ('van', 1),
             ('dormir', 1),
             ('su', 5),
             ('casa', 1),
             ('Está', 2),
             ('Así', 1),
             ('sudas', 1),
             ('luego', 1),
             ('puedes', 3),
             ('traerte', 1),
             ('una', 11),
             ('voy', 4),
             ('paso', 3),
             ('¿Puedes', 1),
             ('sí', 4),
             ('está', 1),
             ('grabando?', 1),
             ('¡Ay,', 1),
             ('¿Alguna', 2),
             ('vez', 4),
             ('han', 15),
             ('algo', 3),
             ('te', 15),
             ('llorar', 1),
             ('trabajo?', 1),
             ('Nunca', 1),
             ('había', 3),
             ('trabajado', 1),
             ('están', 2),
             ('haciendo', 4),
             ('puente', 1),
             ('Se', 4),
             ('Un', 1),
             ('día', 4),
             ('entusiasmo,', 1),
             ('al', 6),
             ('otro', 2),
             ('Bueno,', 2),
             ('entonces', 2),
             ('llamabas', 1),
             ('P', 1),
             ('todo,', 1),
             ('como', 2),
             ('vas', 2),
             ('hace', 3),
             ('Estaba', 2),
             ('muy', 20),
             ('pequeña', 2),
             ('casa,', 1),
             ('Lo', 4),
             ('sea', 1),
             ('menos', 3),
             ('Venden', 1),
             ('tostadas', 1),
             ('A', 11),
             ('veces', 6),
             ('le', 7),
             ('echo', 3),
             ('carne', 1),
             ('llevas', 1),
             ('vecinos?', 1),
             ('Bien,', 1),
             ('sales', 1),
             ('todo', 9),
             ('eso', 7),
             ('Ya', 5),
             ('tiempo', 1),
             ('Me', 5),
             ('gustaba', 2),
             ('leer', 1),
             ('sé', 1),
             ('por', 10),
             ('ve', 1),
             ('joven', 1),
             ('él', 2),
             ('da', 4),
             ('Para', 1),
             ('clase', 1),
             ('otra', 3),
             ('bonito', 1),
             ('Quieres', 1),
             ('dormir,', 1),
             ('pasasan', 1),
             ('yo', 7),
             ('era', 9),
             ('niño', 1),
             ('fútbol', 1),
             ('Ahora', 3),
             ('tenemos', 1),
             ('ir', 2),
             ('estadio,', 1),
             ('antes', 2),
             ('¿Cómo', 4),
             ('consideras', 1),
             ('tu', 3),
             ('mamá?', 1),
             ('Es', 3),
             ('Los', 1),
             ('quieren', 2),
             ('madera,', 1),
             ('plástico', 1),
             ('control', 1),
             ('remoto', 1),
             ('tan', 3),
             ('mueves', 1),
             ('va', 1),
             ('donde', 2),
             ('quieras', 1),
             ('aquí', 2),
             ('allá,', 1),
             ('mis', 2),
             ('sufrimiento', 1),
             ('mi', 14),
             ('jefe,', 1),
             ('Yo', 12),
             ('conozco,', 1),
             ('¡Qué', 2),
             ('vaya', 1),
             ('bien!', 1),
             ('quedaba', 1),
             ('aquí,', 1),
             ('mí', 4),
             ('verdad', 2),
             ('bien', 6),
             ('hermano', 3),
             ('¿De', 3),
             ('durante', 2),
             ('vacaciones?', 1),
             ('ahí', 4),
             ('algún', 2),
             ('sitio', 1),
             ('dónde', 2),
             ('Como', 3),
             ('padre', 1),
             ('hasta', 2),
             ('bastante', 3),
             ('mayor,', 1),
             ('seis', 2),
             ('mañana', 2),
             ('dos', 4),
             ('minutos', 2),
             ('estás', 2),
             ('allí', 1),
             ('hora', 1),
             ('atravesado', 1),
             ('ciudad', 2),
             ('entera', 1),
             ('lápiz,', 1),
             ('apuntaba', 1),
             ('recetas', 1),
             ('fiestas', 1),
             ('locales', 1),
             ('Menos', 1),
             ('mal', 1),
             ('Sí,', 3),
             ('muchas', 3),
             ('horas', 1),
             ('Vienen', 1),
             ('muchos', 2),
             ('jóvenes', 1),
             ('nunca', 1),
             ('usaba', 1),
             ('Y', 2),
             ('espacio', 1),
             ('quince', 1),
             ('minutos,', 1),
             ('llover', 1),
             ('Salgo', 1),
             ('camino', 1),
             ('par', 1),
             ('Tengo', 1),
             ('nos', 3),
             ('Vamos', 1),
             ('ver', 2),
             ('Esa', 2),
             ('estado', 3),
             ('¿Dónde', 1),
             ('queda', 1),
             ('periódicos', 1),
             ('aquí?', 2),
             ('diez', 1),
             ('venir,', 1),
             ('vengo', 1),
             ('Llevo', 1),
             ('mes', 1),
             ('sin', 1),
             ('venir', 1),
             ('relaciones', 1),
             ('entre', 1),
             ('también', 3),
             ('¿Cuántos', 2),
             ('Somos', 1),
             ('Hay', 1),
             ('puede', 1),
             ('todos', 2),
             ('podría', 1),
             ('eso?', 3),
             ('Todas', 1),
             ('atascadas,', 1),
             ('llenas', 1),
             ('fiesta?', 1),
             ('Con', 2),
             ('tienes', 2),
             ('ni', 1),
             ('bar', 1),
             ('Juntos,', 1),
             ('otros', 1),
             ('peligroso,', 1),
             ('así', 2),
             ('moto', 1),
             ('Mi', 3),
             ('novia', 1),
             ('apuntar', 1),
             ('sacaros', 1),
             ('Llevaba', 1),
             ('detrás', 1),
             ('Toquemos', 1),
             ('madera', 1),
             ('¿No?', 2),
             ('Que', 2),
             ('nada', 4),
             ('nadie', 1),
             ('idea', 1),
             ('mirado', 1),
             ('así?', 1),
             ('hermanos', 1),
             ('pequeños', 1),
             ('allí?', 1),
             ('vacaciones', 1),
             ('comidas', 1),
             ('noche', 1),
             ('vieja', 1),
             ('casa?', 2),
             ('ahí?', 1),
             ('Cada', 1),
             ('año', 1),
             ('veo', 1),
             ('¿Tú', 3),
             ('dedicas?', 1),
             ('Soy', 1),
             ('camarero', 2),
             ('Te', 3),
             ('les', 3),
             ('quedas', 1),
             ('viendo', 1),
             ('directamente', 1),
             ('ojos,', 1),
             ('¿Más', 1),
             ('grandes', 2),
             ('según', 1),
             ('eran', 1),
             ('incluso', 1),
             ('periódico', 1),
             ('La', 4),
             ('sabía', 2),
             ('¿Cual', 1),
             ('lugar', 1),
             ('hayas', 1),
             ('metido?', 1),
             ('cambiar', 1),
             ('vida?', 1),
             ('Era', 1),
             ('rápido', 1),
             ('Ella', 2),
             ('única', 1),
             ('persona', 1),
             ('caía', 1),
             ('alguna', 3),
             ('nevada', 1),
             ('pasabas.', 1),
             ('días', 1),
             ('nevada?', 1),
             ('uno', 1),
             ('amigos,', 1),
             ('metí', 1),
             ('¿Se', 2),
             ('construcciones', 1),
             ('nuevas?', 1),
             ('sobre', 1),
             ('Tenía', 1),
             ('avisaron', 1),
             ('tenía', 2),
             ('moverlo', 1),
             ('zonas', 2),
             ('habrá', 1),
             ('¿Siempre', 1),
             ('mismos?', 1),
             ('asociados', 1),
             ('manera?', 1),
             ('hacerlo', 1),
             ('cualquier', 1),
             ('primero', 1),
             ('comprarme', 1),
             ('sartén,', 1),
             ('pones', 1),
             ('dorar', 1),
             ('ajo.', 1),
             ('Después', 1),
             ('cucharada', 1),
             ('echas', 1),
             ('remueves', 1),
             ('encantaría', 1),
             ('normal.', 1),
             ('ojos', 1),
             ('azules', 1),
             ('Tranquilo,', 1),
             ('todo.', 1),
             ('ayudar', 1),
             ('Qué', 1),
             ('difícil', 2),
             ('vivo', 1),
             ('él,', 1),
             ('dió', 1),
             ('opinión', 1),
             ('ella', 1),
             ('verme', 1),
             ('bailar.', 1),
             ('fue', 1),
             ('historia', 1),
             ('Entonces', 3),
             ('empecé', 1),
             ('salir', 4),
             ('construimos', 1),
             ('especie', 1),
             ('viviendo', 1),
             ('vender', 1),
             ('eso.', 1),
             ('¿Sabes', 1),
             ('propuesta', 1),
             ('mucho?', 1),
             ('¿Quién', 1),
             ('ese', 2),
             ('montaje?', 1),
             ('hablar', 1),
             ('Pero', 2),
             ('interesante', 1),
             ('antes,', 1),
             ('niño,', 1),
             ('hacía', 1),
             ('este', 2),
             ('también?', 1),
             ('soy', 1),
             ('situaciones', 1),
             ('Tú', 1),
             ('sentías', 1),
             ('ayudándoles', 1),
             ('Les', 1),
             ('servíamos', 1),
             ('comida,', 1),
             ('hojas', 1),
             ('patio,', 1),
             ('¿Pero', 1),
             ('Parece', 1),
             ('funciona', 1),
             ('amigo', 1),
             ('mío', 1),
             ('cosas', 1),
             ('siete', 2),
             ('Creo', 1),
             ('¿Cuándo', 1),
             ('salen', 1),
             ('El', 1),
             ('chico', 1),
             ('infantil', 1),
             ('edad.', 1),
             ('veía', 1),
             ('mayor.', 1),
             ('ganabas', 1),
             ('poder', 1),
             ('decir', 1),
             ('Ellos', 1),
             ('vi', 1),
             ('imagen', 1),
             ('toda', 2),
             ('familia', 1),
             ('quiso', 1),
             ('preocupacíon', 1),
             ('notaba', 1),
             ('decía', 2),
             ('preocupara', 1),
             ('Tiene', 1),
             ('miedo', 1),
             ('Va', 1),
             ('ser', 1),
             ('vuelva', 1),
             ('confianza.', 1),
             ('"Señor,', 1),
             ('déme', 1),
             ('demostrarle', 1),
             ('puedo', 1),
             ('hacer"', 1),
             ('¡Felicidades!', 1),
             ('quedó', 1),
             ('Tu', 1),
             ('proyecto', 1),
             ('¡Me', 1),
             ('enero,', 1),
             ('Desde', 1),
             ('meses', 1),
             ('pude', 1),
             ('haber', 1),
             ('nuevo,', 1),
             ('quise', 1),
             ('aventurar', 1),
             ('tanto', 1),
             ('todavía', 1),
             ('preocupación', 1),
             ('carpinteros', 1),
             ('Fui', 1),
             ('oficina', 1),
             ('apagué', 1),
             ('llevaba', 1),
             ('nuevo', 1),
             ('poco', 3),
             ('¿El', 1),
             ('esta', 1),
             ('explícame', 1),
             ('hoy', 1),
             ('No,', 1),
             ('portero', 1),
             ('vida', 2),
             ('bastantes', 1),
             ('pocos?', 1),
             ('Durante', 1),
             ('partido,', 1),
             ('mano', 1),
             ('Donde', 1),
             ('yo,', 1),
             ('hacemos', 1),
             ('muestras', 1),
             ('algo?', 2),
             ('hotel?', 1),
             ('avión?', 1),
             ('pensado', 1),
             ('hacer?', 1),
             ('cuesta', 1),
             ('fiesta', 1),
             ('trabajaba', 1),
             ('hermana', 1),
             ('¿Todos', 1),
             ('pueblo?', 1),
             ('tal?', 1),
             ('cuaresma?', 1),
             ('planes', 1),
             ('esperas?', 1),
             ('siento', 1),
             ('trabajar', 1),
             ('papá', 1),
             ('tiene', 2),
             ('oportunidades', 1),
             ('universidad', 1),
             ('pública,', 1),
             ('realmente', 2),
             ('patio', 1),
             ('papel', 1),
             ('sea,', 1),
             ('Ir', 1),
             ('viaje', 1),
             ('Las', 1),
             ('clases', 1),
             ('usted', 1),
             ('día?', 1),
             ('llego', 1),
             ('miro', 1),
             ('cocinar', 1),
             ('¿no?', 1),
             ('Sí', 1),
             ('gusta,', 1),
             ('hago', 1),
             ('madre', 1),
             ('¿Cada', 1),
             ('cuanto', 1),
             ('visita', 1),
             ('normalmente', 1),
             ('navidad?', 1),
             ('¡Que', 1),
             ('aquel', 1),
             ('escuchar', 1),
             ('radio', 1),
             ('¿Usas', 1),
             ('estudiar', 1),
             ('¿Envías', 1),
             ('recibes', 1),
             ('mensajes', 1),
             ('trabajas', 1),
             ('músico,', 1),
             ('toco', 1),
             ('hoteles', 1),
             (',', 1),
             ('eventos', 1),
             ('privados', 1),
             ('hay', 1)])

In [ ]:
dict(ps_count) - dict(ms_count)

TypeError: unsupported operand type(s) for -: 'dict' and 'dict'

In [5]:
df = pd.read_csv('/content/SpanishDialectDiscrimination/Data/Working_Sentence_Dataset.csv')

In [7]:
df[(df['MS_Check'].notnull() | df['PS_Check'].notnull())]

,Sentence_ID,Text ID,Line,Speaker,Raw,PS,PS_Check,PS_Note,MS,MS_Check,MS_Note,English,Type
1,2.0,ALCA_H11_037,11,I,he cambiado / porque la otra vez / la niña est...,"He cambiado, porque la niña estaba en el coleg...",NaN,NaN,"Cambié, porque la niña estaba en la escuela, p...",X,"Cambié, porque la niña estaba en la escuela, p...","I changed, because the girl was in school, but...",B
8,NaN,ALCA_H11_037,61,I,hacer los líos con tus amiguetes,Hacer líos con tus amiguetes,x,Que es hacer lios?,Hacer desmadre con tus compas,X,Hacer desmadre con tus cuates/ compas (compas ...,Make trouble with your pals,L
11,NaN,ALCA_H11_037,68,I,cuando terminaba el colegio a las seis estabas...,"Cuando terminaba el colegio a las seis, estaba...",NaN,NaN,"Cuando terminaba la escuela a las seis, estaba...",X,"en vez de colegio yo diria escuela, se usa muc...","When school was over at six, you were on the s...",L
13,NaN,ALCA_H11_037,"(78,80)",B,¿qué y qué salís / casi siempre 78 I: sí 79...,¿Salís vosotros casi siempre con los mismos am...,NaN,NaN,¿Salen ustedes casi siempre con los mismos ami...,X,Normalmente con un chavo que es con el que mej...,Do you (plural) usually go out with the same f...,B
16,NaN,ALCA_H12_019,103,I,cogen el coche o sus medios y se van a dormir ...,Cogen el coche y se van a dormir a su casa,NaN,NaN,Agarran el carro y se van a dormir a su casa,X,Agarraron el carro y se fueron a dormir a su casa,They take the car and they go home to sleep,L
21,NaN,GUAD_H12_098,243,E,¿alguna vez te echaron la culpa por algo que t...,¿Alguna vez han echado la culpa por algo que t...,NaN,NaN,¿Alguna vez te echaron la culpa por algo que t...,X,Alguna vez te culparon por algo que tu no hici...,Have you ever been blamed for something you di...,G
28,NaN,GUAD_H13_014,19,I,se enoja de todo pero pues ni modo que te enoj...,"Se enfada de todo, pero como te vas a enfadar ...",NaN,NaN,"Se enoja de todo, pero ni modo que te enojes p...",X,"""Se enoja por todo"" en vez de ""Se enoja de todo""","They get mad about everything, but how are you...",L
45,NaN,GUAD_H21_060,100,NaN,me la paso aquí y allá y allá / cotorreando co...,"Me la paso aquí y allá, charlando con mis colegas",NaN,NaN,"Me la paso aquí y allá, cotorreando con mis co...",X,"""Cotorreando con mis compas""","I go from here to there, chatting with frends",NaN
49,NaN,GRAN_M21_046,1,NaN,a mí la verdad es que muy bien no se me ha dad...,A mí la verdad es que no se me ha dado muy bie...,NaN,NaN,A mí la verdad es que no se me dió muy bien la...,X,Se podria decir la verdad pero tambien se usa ...,"Truth is, I was not very good at school",Both
52,NaN,GRAN_M21_046,10,NaN,¿y las vacaciones? // a // ¿os ibais por ahí a...,¿Y las vacaciones? ¿Os ibais vosotros por ahí ...,NaN,NaN,¿Y las vacaciones? ¿Se iban ustedes por ahí a ...,X,"""o a donde fueron?""",And holidays? Would you go somewhere or where ...,Grammar
53,NaN,GRAN_M21_046,10,NaN,como mi padre no ha tenido coche hasta // ya b...,Como mi padre no ha tenido coche hasta ya bast...,NaN,NaN,Como mi padre no tuvo carro hasta ya bastante ...,X,"""Como mi papa no tuvo carro hasta que era bast...",Since my father didn't have a car untill he wa...,Both
83,NaN,MADR_H11_002,266,NaN,ya lo he comprendido y // la he vendido para eso,"Ya lo he comprendido, y he vendido mi moto",NaN,NaN,"Ya lo entendí, y vendí mi moto",X,"""Ya entendi""","I understand now, and I sold my motorcycle",Grammar
84,NaN,MADR_H11_002,"(277, 278)",NaN,nos vamos a apuntar mi novia y yo a la autoesc...,Mi novia y yo nos vamos a apuntar a la autoesc...,x,mal conjugado,Mi novia y yo nos vamos a apuntar a la escuela...,NaN,NaN,My girlfriend and I are going to sign up for d...,Lexical
103,NaN,MEXI_H11_078,433,I,era muy muy enojón también / o sea me me me vi...,"Era muy enfadadizo, me enfadaba muy rápido",x,nunca he oido enojadizo,"Era muy enojón, me enojaba muy rápido",NaN,NaN,"I was very short-tempered, I got angry very qu...",Lexical
105,NaN,MADR_H12_007,"(36, 37)",I,hemos tenido / 37 E: ya 37 I: un tiempo ba...,"Hemos tenido un tiempo bastante bueno, pero ah...",NaN,NaN,"Hubo buen clima, pero ahora nos vino la ola de...",X,"""Hubo buen clima""","We had quite good weather, but now the cold sn...",Grammar
106,NaN,MADR_H12_007,38,E,¿y tú recuerdas si eso también sucedía antes?...,¿Tú recuerdas si eso también sucedía cuando tú...,NaN,NaN,¿Te acuerdas si eso también pasaba cuando tú e...,X,"""Te acuerdas si te pasaba eso cuando eras chico?""",Do you remember if that also happened when you...,Lexical
125,NaN,MEXI_H12_042,92,I,mi her <palabra_cortada/> / hermano estaba ahí...,"Mi hermano estaba ahí, cotilleando",x,cotilleando,"Mi hermano estaba ahí, de metiche",NaN,NaN,"My brother was there, being nosy",Lexical
136,NaN,MADR_H13_013,110,I,tú te sentías bien ayudándoles / un poquillo /...,Tú te sentías bien ayudándoles un poquillo. Le...,NaN,NaN,Tú te sentías bien ayudándoles un poquito. Les...,X,"""recogimos las hojas en el patio y platicabamos""",You'd feel good helping them a little. We'd se...,Lexical
167,NaN,BCN_H12_037,26,I,yo me he hecho daño en la mano y un rato no he...,Me he hecho daño en la mano y he dejado de jugar,NaN,NaN,Me lastimé la mano y dejé de jugar,X,"""Me lastime la mano y deje de jugar""",I hurt my hand and didn't play for a while,Grammar
187,NaN,BARC_H13_002,"(275, 276)",I,cuando llego yo pues me miro la nevera 276 E: ...,"Cuando llego a mi piso, pues miro en la nevera...",NaN,NaN,"Cuando llego a mi apartamento, pues miro en el...",X,"""Miro en el refrigerador para ver que tengo""","When I get to my apartment, I look in the frid...",Lexical
197,NaN,MONR_H13_025,314,E,¿envías y mensajes / y recibes / por celular?,¿Envías y recibes mensajes por el móvil?,x,por el,¿Envías y recibes mensajes por celular?,NaN,NaN,Do you send and receive messages by mobile phone?,Lexical

In [24]:
t_df = df[(df['MS_Check'].notnull() | df['PS_Check'].notnull())]['Text ID'].value_counts()


o_ps = 0
o_ms = 0

for i in t_df.index:
  if 'MONR' in i or 'MEXI' in i or 'GUAD' in i:
    o_ms = o_ms + t_df[i]
  else:
    o_ps = o_ps + t_df[i]
  print(i,t_df[i])

ALCA_H11_037 4
GRAN_M21_046 3
MADR_H12_007 2
MADR_H11_002 2
ALCA_H12_019 1
GUAD_H12_098 1
GUAD_H21_060 1
GUAD_H13_014 1
MEXI_H11_078 1
MEXI_H12_042 1
MADR_H13_013 1
BCN_H12_037 1
BARC_H13_002 1
MONR_H13_025 1

In [32]:
ps = 0
ms = 0
for i in df[(df['MS_Check'].notnull() | df['PS_Check'].notnull())]['Text ID'].values:
 if 'MONR' in i or 'MEXI' in i or 'GUAD' in i:
  ms = ms + 1
else:
  ps = ps + 1

print(ps,ms)

1 6

In [25]:
print(o_ps, o_ms)

15 6

In [23]:
'MONR'in'MONR_H13_025'

True

In [9]:
len(df[(df['MS_Check'].notnull() | df['PS_Check'].notnull())])

21

In [8]:
df[(df['MS_Check'].notnull() | df['PS_Check'].notnull())]['MS'][187]

'Cuando llego a mi apartamento, pues miro en el refrigerador para ver de que tengo'